name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '52 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Run scraper
      run: python scrape.py
    - name: Commit and push if it changed
      run: |-
        git config --global user.name "scraper-bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Scraped at ${timestamp}" || exit 0
        git push
